var clubs = ["Argentinos Jrs.","Bahía Blanca","Banfield","Belgrano","Boca Juniors","Estudiantes","Fl. Varela",
"G. La Plata","Godoy Cruz","Independiente","Junín","Lanús","Mar del Plata","Mataderos","Newell's","Parque Patricios",
"Posadas","Quilmes","Racing Club","Rafaela","River Plate","Rosario Central","San Juan","San Lorenzo","Santa Fe","Sarandí",
"Temperley","Tigre","Unión","Vélez Sarsfield","Adelaide United","Brisbane Roar","Central Coast","Melb. Victory","Melbourne City",
"Newcastle Jets","Perth Glory","Sydney FC","Well. Phoenix","WS Wanderers","Admira Wacker","Austria Wien","RB Salzburg",
"SCR Altach","SK Rapid Wien","SK Sturm Graz","SV Grödig","SV Mattersburg","SV Ried","Wolfsberger AC","Club Brugge",
"KAA Gent","KRC Genk","KV Kortrijk","KV Mechelen","KV Oostende","KVC Westerlo","OH Leuven","Royal Mouscron","RSC Anderlecht",
"Sint-Truiden","Sp. Charleroi","Sport. Lokeren","Standard Liège","Waasl. Beveren","Zulte-Waregem","Audax Italiano",
"CD Antofagasta","CD Cobresal","CD Huachipato","CD O'Higgins","CD Palestino","Colo-Colo","Depor. Iquique","San Luis","San Marcos","Uni. Católica",
"Uni. Concepción","Uni. de Chile","Unión Española","Unión La Calera","Wanderers","Águilas Doradas","Al. Petrolera","Atl. Nacional",
"Atlético Huila","Boyacá Chicó","Cortuluá","Cúcuta Depor.","Deportes Tolima","Deportivo Cali","Deportivo Pasto","Envigado",
"Ind. Santa Fe","Indep. Medellín","Jaguares","Junior","La Equidad","Millonarios","Once Caldas","Patriotas","Uniautónoma",
"Aalborg BK","Aarhus GF","Brøndby IF","Esbjerg fB","FC København","FC Midtjylland","FC Nordsjælland","Hobro IK","Odense BK",
"Randers FC","SønderjyskE","Viborg FF","Arsenal","Aston Villa","Bournemouth","Chelsea","Crystal Palace","Everton","Leicester City",
"Liverpool","Manchester City","Manchester Utd","Newcastle Utd","Norwich","Southampton","Spurs","Stoke City","Sunderland",
"Swansea City","Watford","West Brom","West Ham","Birmingham City","Blackburn Rovers","Bolton","Brentford","Brighton","Bristol City",
"Burnley","Cardiff City","Charlton Ath","Derby County","Fulham","Huddersfield","Hull City","Ipswich","Leeds United","Middlesbrough",
"MK Dons","Nott'm Forest","Preston","QPR","Reading","Rotherham Utd","Sheffield Wed","Wolves","Barnsley","Blackpool",
"Bradford City","Burton Albion","Bury","Chesterfield","Colchester","Coventry City","Crewe Alexandra","Doncaster","Fleetwood Town","Gillingham",
"Millwall","Oldham Athletic","Peterborough","Port Vale","Rochdale","Scunthorpe Utd","Sheffield Utd","Shrewsbury",
"Southend United","Swindon Town","Walsall","Wigan Athletic","Accrington","AFC Wimbledon","Barnet","Bristol Rovers",
"Cambridge Utd","Carlisle United","Crawley Town","Dag & Red","Exeter City","Hartlepool","Leyton Orient","Luton Town",
"Mansfield Town","Morecambe","Newport County","Northampton","Notts County","Oxford United","Plymouth Argyle","Portsmouth",
"Stevenage","Wycombe","Yeovil Town","York City","Angers SCO","AS Monaco","AS Saint-Étienne","EA Guingamp","ES Troyes AC",
"FC Lorient","FC Nantes","GFC Ajaccio","Giron. Bordeaux","LOSC Lille","Montpellier HSC","OGC Nice","Olym. Lyonnais",
"Olym. Marseille","PSG","SC Bastia","SM Caen","Stade de Reims","Stade Rennais","Toulouse FC","AC Ajaccio","AJ Auxerre",
"AS Nancy","Bourg-Péronnas","Cham. Niortais","Clermont Foot","Dijon FCO","Évian TG","FC Metz","FC Sochaux","Le Havre AC",
"Nîmes Olympique","Paris FC","RC Lens","Red Star FC","Stade Brestois","Stade Lavallois","Tours FC","US Créteil",
"Valenciennes FC","1. FC Köln","1. FSV Mainz 05","1899 Hoffenheim","Bayer 04","Bor. Dortmund","Bor. M'gladbach",
"Eint. Frankfurt","FC Augsburg","FC Bayern","FC Ingolstadt","FC Schalke 04","Hamburger SV","Hannover 96",
"Hertha BSC","SV Darmstadt","VfB Stuttgart","VfL Wolfsburg","Werder Bremen","1. FC Heidenheim","1. FC Nürnberg",
"1860 München","Arminia Bielefeld","Braunschweig","F. Düsseldorf","FC St. Pauli","FSV Frankfurt","Greuther Fürth",
"Kaiserslautern","Karlsruher SC","MSV Duisburg","RB Leipzig","SC Freiburg","SC Paderborn","SV Sandhausen",
"Union Berlin","VfL Bochum","Atalanta","Bologna","Carpi","Chievo Verona","Empoli","Fiorentina","Frosinone",
"Genoa","Hellas Verona","Inter","Juventus","Lazio","Milan","Napoli","Palermo","Roma","Sampdoria","Sassuolo","Torino","Udinese","Ascoli",
"Avellino","Bari","Brescia","Cagliari","Cesena","Chiavari","Como","Crotone",
"La Spezia","Lanciano","Latina","Livorno","Modena","Novara","Perugia","Pescara","Salerno","Terni","Trapani",
"Vercelli","Vicenza","Busan IPark","Daejeon Citizen","FC Seoul","GwangJu FC","Incheon United",
"Jeju United","Jeonbuk Hyundai","Jeonnam Dragons","Pohang Steelers","Seongnam FC","Suwon Bluewings",
"Ulsan Hyundai","América","Atlas","Chiapas","Cruz Azul","Dorados","Guadalajara","León","Monarcas Morelia",
"Monterrey","Pachuca","Puebla","Querétaro","Santos Laguna","Tigres","Tijuana","Toluca","U.N.A.M.","Veracruz",
"ADO Den Haag","Ajax","AZ","De Graafschap","Excelsior","FC Groningen","FC Twente","FC Utrecht","Feyenoord",
"Heracles Almelo","N.E.C.","PEC Zwolle","PSV","Roda JC","SC Cambuur","SC Heerenveen","Vitesse","Willem II",
"Aalesunds FK","FK Bodø/Glimt","FK Haugesund","IK Start","Lillestrøm SK","Mjøndalen IF","Molde FK","Odds BK",
"Rosenborg BK","Sandefjord","Sarpsborg 08 FF","Stabæk Fotball","Strømsgodset IF","Tromsø IL","Vålerenga Fotball",
"Viking FK","Cracovia","Górnik Łęczna","Górnik Zabrze","Jagiellonia","Korona Kielce","Lech Poznań","Lechia Gdańsk",
"Legia Warszawa","Piast Gliwice","Podbeskidzie","Pogoń Szczecin","Ruch Chorzów","Śląsk Wrocław","Termalica","Wisła Kraków",
"Zagłębie Lubin","Académica","Arouca","Belenenses","Boavista","Estoril Praia","FC Porto","Madeira","Marítimo","Moreirense",
"Nacional","Paços Ferreira","Rio Ave","SC Braga","SL Benfica","Sporting CP","Tondela","V. Guimarães","V. Setúbal","Bohemian FC",
"Bray Wanderers","Cork City","Derry City","Drogheda Utd","Dundalk","Galway United","Limerick","Longford Town","Shamrock Rovers","Sligo Rovers",
"St. Pats","adidas All-Star","Atlético Mineiro","Atl. Paranaense","Avaí","Classic XI","Chapecoense",
"Coritiba","Cruzeiro","Figueirense","Fluminense","Grêmio","Joinville","Internacional","Kaizer Chiefs","MLS All Stars","Olympiakos CFP",
"Orlando Pirates","Palmeiras","Panathinaikos","PAOK","Ponte Preta","Santos","São Paulo","Shakhtar Donetsk","Vasco da Gama","World XI",
"Amkar Perm","Anzhi Makhachkala","CSKA Moscow","Dinamo Moscow","FC Krasnodar","FC Rostov","FC Ufa","FC Ural","Krylya Sovetov","Kuban Krasnodar",
"Lokomotiv Moscow","Mordovia Saransk","Rubin Kazan","Spartak Moscow","Terek Grozny","Zenit","Al Ahli","Al Faisaly","Al Fateh","Al Hilal",
"Al Ittihad","Al Khaleej","Al Nassr","Al Qadisiyah","Al Raed","Al Shabab","Al Taawoun","Al Wehda","Hajer","Najran","Aberdeen","Celtic",
"Dundee FC","Dundee United","Hamilton","Hearts","Inverness CT","Kilmarnock","Motherwell","Partick Thistle","Ross County","St. Johnstone ",
"Athletic Bilbao","Atlético Madrid","Celta Vigo","FC Barcelona","Getafe CF","Granada CF","Levante UD","Málaga CF","Rayo Vallecano","RC Deportivo",
"RCD Espanyol","Real Betis","Real Madrid","Real Sociedad","SD Eibar","Sevilla FC","Sporting Gijón","UD Las Palmas","Valencia CF",
"Villarreal CF ","AD Alcorcón","Albacete","Bilbao Athletic","CA Osasuna","CD Leganés","CD Lugo","CD Mirandés","CD Numancia","CD Tenerife",
"Córdoba CF","Deport. Alavés","Elche CF","Gimnàstic","Girona CF","RCD Mallorca","Real Oviedo","Real Valladolid","Real Zaragoza","SD Huesca",
"SD Ponferradina","UD Almería","UE Llagostera ","AIK","Åtvidabergs FF","BK Häcken","Djurgårdens IF","Falkenbergs FF","Gefle IF","GIF Sundsvall",
"Halmstads BK","Hammarby","Helsingborgs IF","IF Elfsborg","IFK Göteborg","IFK Norrköping","Kalmar FF","Malmö FF","Örebro SK ",
"BSC Young Boys","FC Basel","FC Lugano","FC Luzern","FC Sion","FC St. Gallen","FC Thun","FC Vaduz","FC Zürich","Grasshopper ","Akhisarspor",
"Antalyaspor","Beşiktaş","Bursaspor","Çaykur Rizespor","Eskişehirspor","Fenerbahçe","Galatasaray","Gaziantepspor","Gençlerbirliği","Kasimpaşa",
"Kayserispor","Konyaspor","Medipol Başakşehir","Mersin","Osmanlıspor","Sivasspor","Trabzonspor ","Chicago Fire","Colorado Rapids",
"Columbus Crew SC","D.C. United","FC Dallas","Houston Dynamo","LA Galaxy","Montreal Impact","New England","NY Red Bulls",
"NYCFC","Orlando City","Philadelphia","Portland","Real Salt Lake","SJ Earthquakes","Sounders FC","Sporting KC","Toronto FC",
"Whitecaps FC ","Argentina","Australia","Austria","Belgium","Bolivia","Brazil","Bulgaria","Cameroon","Canada","Chile","China PR",
"Colombia","Côte d'Ivoire","Czech Republic","Denmark","Ecuador","Egypt","England","Finland","France","Germany","Greece",
"Hungary","India","Ireland","Italy","Mexico","Netherlands","New Zealand","Northern Ireland","Norway","Paraguay","Peru","Poland","Portugal","Romania","Russia",
"Scotland","Slovenia","South Africa","Spain","Sweden","Switzerland","Turkey","United States","Uruguay","Venezuela",
"Wales","Australia (W)","Brazil (W)","Canada (W)","China PR (W)","England (W)","France (W)","Germany (W)","Italy (W)",
"Mexico (W)","Spain (W)","Sweden (W)","United States (W)"];
